regex:
  email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
user:
  validates:
    password:
      min: 6
    name:
      max: 50
product:
  validates:
    name:
      max: 100
    price:
      max: 100000000
      min: 0
  paginates: 12
blob:
  size:
    small: [800, 600]
    large: [1024, 768]
display:
  product_name: 40
  slides:
    product_items: 15
