name: ğŸš€ Continuous deployment to EC2 AWS

on:
  push:
    branches:
      - main  # hoáº·c master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: self-hosted

    steps:
      - name: â¬ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ§° Deploy app (stop â†’ build â†’ up)
        run: |
          echo "ğŸš€ Starting containers..."
          docker compose up -d --build

          echo "âœ… Deployment done."
          docker ps -a
